// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * <!-- subcategory:Authors -->List all available Authors.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as readarr from "@pulumi/readarr";
 *
 * const example = readarr.Authors.getAuthors({});
 * ```
 */
export function getAuthors(opts?: pulumi.InvokeOptions): Promise<GetAuthorsResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("readarr:Authors/getAuthors:getAuthors", {
    }, opts);
}

/**
 * A collection of values returned by getAuthors.
 */
export interface GetAuthorsResult {
    /**
     * Author list.
     */
    readonly authors: outputs.Authors.GetAuthorsAuthor[];
    /**
     * The ID of this resource.
     */
    readonly id: string;
}
