// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * <!-- subcategory:Metadata -->Metadata Config.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as readarr from "@pulumi/readarr";
 *
 * const example = readarr.Metadata.getMetadataConfig({});
 * ```
 */
export function getMetadataConfig(opts?: pulumi.InvokeOptions): Promise<GetMetadataConfigResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("readarr:Metadata/getMetadataConfig:getMetadataConfig", {
    }, opts);
}

/**
 * A collection of values returned by getMetadataConfig.
 */
export interface GetMetadataConfigResult {
    /**
     * Embed metadata in book files.
     */
    readonly embedMetadata: boolean;
    /**
     * Metadata Config ID.
     */
    readonly id: number;
    /**
     * Scrub audio tags.
     */
    readonly scrubAudioTags: boolean;
    /**
     * Update covers.
     */
    readonly updateCovers: boolean;
    /**
     * Write audio tags.
     */
    readonly writeAudioTags: string;
    /**
     * Write book tags.
     */
    readonly writeBookTags: string;
}
