// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { GetMetadataConfigResult } from "./getMetadataConfig";
export const getMetadataConfig: typeof import("./getMetadataConfig").getMetadataConfig = null as any;
utilities.lazyLoad(exports, ["getMetadataConfig"], () => require("./getMetadataConfig"));

export { MetadataConfigArgs, MetadataConfigState } from "./metadataConfig";
export type MetadataConfig = import("./metadataConfig").MetadataConfig;
export const MetadataConfig: typeof import("./metadataConfig").MetadataConfig = null as any;
utilities.lazyLoad(exports, ["MetadataConfig"], () => require("./metadataConfig"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "readarr:Metadata/metadataConfig:MetadataConfig":
                return new MetadataConfig(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("readarr", "Metadata/metadataConfig", _module)
