// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * <!-- subcategory:Profiles -->Single Metadata Profile.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as readarr from "@pulumi/readarr";
 *
 * const example = readarr.Profiles.getMetadataProfile({
 *     name: "Example",
 * });
 * ```
 */
export function getMetadataProfile(args: GetMetadataProfileArgs, opts?: pulumi.InvokeOptions): Promise<GetMetadataProfileResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("readarr:Profiles/getMetadataProfile:getMetadataProfile", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getMetadataProfile.
 */
export interface GetMetadataProfileArgs {
    /**
     * Metadata Profile name.
     */
    name: string;
}

/**
 * A collection of values returned by getMetadataProfile.
 */
export interface GetMetadataProfileResult {
    /**
     * Allowed languages. Comma separated list of ISO 639-3 language codes.
     */
    readonly allowedLanguages: string;
    /**
     * Metadata Profile ID.
     */
    readonly id: number;
    /**
     * Terms to ignore. Comma separated list.
     */
    readonly ignored: string;
    /**
     * Minimum pages.
     */
    readonly minPages: number;
    /**
     * Minimum popularity.
     */
    readonly minPopularity: number;
    /**
     * Metadata Profile name.
     */
    readonly name: string;
    /**
     * Skip missing date.
     */
    readonly skipMissingDate: boolean;
    /**
     * Skip missing ISBN.
     */
    readonly skipMissingIsbn: boolean;
    /**
     * Skip parts and sets.
     */
    readonly skipPartsAndSets: boolean;
    /**
     * Skip secondary series books.
     */
    readonly skipSeriesSecondary: boolean;
}
/**
 * <!-- subcategory:Profiles -->Single Metadata Profile.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as readarr from "@pulumi/readarr";
 *
 * const example = readarr.Profiles.getMetadataProfile({
 *     name: "Example",
 * });
 * ```
 */
export function getMetadataProfileOutput(args: GetMetadataProfileOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetMetadataProfileResult> {
    return pulumi.output(args).apply((a: any) => getMetadataProfile(a, opts))
}

/**
 * A collection of arguments for invoking getMetadataProfile.
 */
export interface GetMetadataProfileOutputArgs {
    /**
     * Metadata Profile name.
     */
    name: pulumi.Input<string>;
}
