// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * <!-- subcategory:Profiles -->Single Quality.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as readarr from "@pulumi/readarr";
 *
 * const example = readarr.Profiles.getQuality({
 *     name: "EPUB",
 * });
 * ```
 */
export function getQuality(args: GetQualityArgs, opts?: pulumi.InvokeOptions): Promise<GetQualityResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("readarr:Profiles/getQuality:getQuality", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getQuality.
 */
export interface GetQualityArgs {
    /**
     * Quality Name.
     */
    name: string;
}

/**
 * A collection of values returned by getQuality.
 */
export interface GetQualityResult {
    /**
     * Quality  ID.
     */
    readonly id: number;
    /**
     * Quality Name.
     */
    readonly name: string;
}
/**
 * <!-- subcategory:Profiles -->Single Quality.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as readarr from "@pulumi/readarr";
 *
 * const example = readarr.Profiles.getQuality({
 *     name: "EPUB",
 * });
 * ```
 */
export function getQualityOutput(args: GetQualityOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetQualityResult> {
    return pulumi.output(args).apply((a: any) => getQuality(a, opts))
}

/**
 * A collection of arguments for invoking getQuality.
 */
export interface GetQualityOutputArgs {
    /**
     * Quality Name.
     */
    name: pulumi.Input<string>;
}
