// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * <!-- subcategory:Media Management -->Single Root Folder.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as readarr from "@pulumi/readarr";
 *
 * const example = readarr.MediaManagement.getRootFolder({
 *     path: "/example",
 * });
 * ```
 */
export function getRootFolder(args: GetRootFolderArgs, opts?: pulumi.InvokeOptions): Promise<GetRootFolderResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("readarr:MediaManagement/getRootFolder:getRootFolder", {
        "path": args.path,
    }, opts);
}

/**
 * A collection of arguments for invoking getRootFolder.
 */
export interface GetRootFolderArgs {
    /**
     * Root Folder absolute path.
     */
    path: string;
}

/**
 * A collection of values returned by getRootFolder.
 */
export interface GetRootFolderResult {
    /**
     * Access flag.
     */
    readonly accessible: boolean;
    /**
     * Default metadata profile ID.
     */
    readonly defaultMetadataProfileId: number;
    /**
     * Default monitor option.
     */
    readonly defaultMonitorOption: string;
    /**
     * Default metadata profile ID.
     */
    readonly defaultQualityProfileId: number;
    /**
     * List of associated tags.
     */
    readonly defaultTags: number[];
    /**
     * Calibre host.
     */
    readonly host: string;
    /**
     * Root Folder ID.
     */
    readonly id: number;
    /**
     * Is calibre library flag.
     */
    readonly isCalibreLibrary: boolean;
    /**
     * Calibre library.
     */
    readonly library: string;
    /**
     * Root Folder name.
     */
    readonly name: string;
    /**
     * Calibre output profile.
     */
    readonly outputProfile: string;
    /**
     * Calibre password.
     */
    readonly password: string;
    /**
     * Root Folder absolute path.
     */
    readonly path: string;
    /**
     * Calibre Port.
     */
    readonly port: number;
    /**
     * Use SSL for calibre connection.
     */
    readonly useSsl: boolean;
    /**
     * Calibre username.
     */
    readonly username: string;
}
/**
 * <!-- subcategory:Media Management -->Single Root Folder.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as readarr from "@pulumi/readarr";
 *
 * const example = readarr.MediaManagement.getRootFolder({
 *     path: "/example",
 * });
 * ```
 */
export function getRootFolderOutput(args: GetRootFolderOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetRootFolderResult> {
    return pulumi.output(args).apply((a: any) => getRootFolder(a, opts))
}

/**
 * A collection of arguments for invoking getRootFolder.
 */
export interface GetRootFolderOutputArgs {
    /**
     * Root Folder absolute path.
     */
    path: pulumi.Input<string>;
}
