// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * <!-- subcategory:Import Lists -->Single Import List Exclusion.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as readarr from "@pulumi/readarr";
 *
 * const example = readarr.ImportLists.getImportListExclusion({
 *     foreignId: "987",
 * });
 * ```
 */
export function getImportListExclusion(args: GetImportListExclusionArgs, opts?: pulumi.InvokeOptions): Promise<GetImportListExclusionResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("readarr:ImportLists/getImportListExclusion:getImportListExclusion", {
        "foreignId": args.foreignId,
    }, opts);
}

/**
 * A collection of arguments for invoking getImportListExclusion.
 */
export interface GetImportListExclusionArgs {
    /**
     * Musicbrainz ID.
     */
    foreignId: string;
}

/**
 * A collection of values returned by getImportListExclusion.
 */
export interface GetImportListExclusionResult {
    /**
     * Author to be excluded.
     */
    readonly authorName: string;
    /**
     * Musicbrainz ID.
     */
    readonly foreignId: string;
    /**
     * ImportListExclusion ID.
     */
    readonly id: number;
}
/**
 * <!-- subcategory:Import Lists -->Single Import List Exclusion.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as readarr from "@pulumi/readarr";
 *
 * const example = readarr.ImportLists.getImportListExclusion({
 *     foreignId: "987",
 * });
 * ```
 */
export function getImportListExclusionOutput(args: GetImportListExclusionOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetImportListExclusionResult> {
    return pulumi.output(args).apply((a: any) => getImportListExclusion(a, opts))
}

/**
 * A collection of arguments for invoking getImportListExclusion.
 */
export interface GetImportListExclusionOutputArgs {
    /**
     * Musicbrainz ID.
     */
    foreignId: pulumi.Input<string>;
}
