// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { GetImportListArgs, GetImportListResult, GetImportListOutputArgs } from "./getImportList";
export const getImportList: typeof import("./getImportList").getImportList = null as any;
export const getImportListOutput: typeof import("./getImportList").getImportListOutput = null as any;
utilities.lazyLoad(exports, ["getImportList","getImportListOutput"], () => require("./getImportList"));

export { GetImportListExclusionArgs, GetImportListExclusionResult, GetImportListExclusionOutputArgs } from "./getImportListExclusion";
export const getImportListExclusion: typeof import("./getImportListExclusion").getImportListExclusion = null as any;
export const getImportListExclusionOutput: typeof import("./getImportListExclusion").getImportListExclusionOutput = null as any;
utilities.lazyLoad(exports, ["getImportListExclusion","getImportListExclusionOutput"], () => require("./getImportListExclusion"));

export { GetImportListExclusionsResult } from "./getImportListExclusions";
export const getImportListExclusions: typeof import("./getImportListExclusions").getImportListExclusions = null as any;
utilities.lazyLoad(exports, ["getImportListExclusions"], () => require("./getImportListExclusions"));

export { GetImportListsResult } from "./getImportLists";
export const getImportLists: typeof import("./getImportLists").getImportLists = null as any;
utilities.lazyLoad(exports, ["getImportLists"], () => require("./getImportLists"));

export { ImportListArgs, ImportListState } from "./importList";
export type ImportList = import("./importList").ImportList;
export const ImportList: typeof import("./importList").ImportList = null as any;
utilities.lazyLoad(exports, ["ImportList"], () => require("./importList"));

export { ImportListExclusionArgs, ImportListExclusionState } from "./importListExclusion";
export type ImportListExclusion = import("./importListExclusion").ImportListExclusion;
export const ImportListExclusion: typeof import("./importListExclusion").ImportListExclusion = null as any;
utilities.lazyLoad(exports, ["ImportListExclusion"], () => require("./importListExclusion"));

export { ImportListGoodreadsBookshelfArgs, ImportListGoodreadsBookshelfState } from "./importListGoodreadsBookshelf";
export type ImportListGoodreadsBookshelf = import("./importListGoodreadsBookshelf").ImportListGoodreadsBookshelf;
export const ImportListGoodreadsBookshelf: typeof import("./importListGoodreadsBookshelf").ImportListGoodreadsBookshelf = null as any;
utilities.lazyLoad(exports, ["ImportListGoodreadsBookshelf"], () => require("./importListGoodreadsBookshelf"));

export { ImportListGoodreadsListArgs, ImportListGoodreadsListState } from "./importListGoodreadsList";
export type ImportListGoodreadsList = import("./importListGoodreadsList").ImportListGoodreadsList;
export const ImportListGoodreadsList: typeof import("./importListGoodreadsList").ImportListGoodreadsList = null as any;
utilities.lazyLoad(exports, ["ImportListGoodreadsList"], () => require("./importListGoodreadsList"));

export { ImportListGoodreadsOwnedBooksArgs, ImportListGoodreadsOwnedBooksState } from "./importListGoodreadsOwnedBooks";
export type ImportListGoodreadsOwnedBooks = import("./importListGoodreadsOwnedBooks").ImportListGoodreadsOwnedBooks;
export const ImportListGoodreadsOwnedBooks: typeof import("./importListGoodreadsOwnedBooks").ImportListGoodreadsOwnedBooks = null as any;
utilities.lazyLoad(exports, ["ImportListGoodreadsOwnedBooks"], () => require("./importListGoodreadsOwnedBooks"));

export { ImportListGoodreadsSeriesArgs, ImportListGoodreadsSeriesState } from "./importListGoodreadsSeries";
export type ImportListGoodreadsSeries = import("./importListGoodreadsSeries").ImportListGoodreadsSeries;
export const ImportListGoodreadsSeries: typeof import("./importListGoodreadsSeries").ImportListGoodreadsSeries = null as any;
utilities.lazyLoad(exports, ["ImportListGoodreadsSeries"], () => require("./importListGoodreadsSeries"));

export { ImportListLazyLibrarianArgs, ImportListLazyLibrarianState } from "./importListLazyLibrarian";
export type ImportListLazyLibrarian = import("./importListLazyLibrarian").ImportListLazyLibrarian;
export const ImportListLazyLibrarian: typeof import("./importListLazyLibrarian").ImportListLazyLibrarian = null as any;
utilities.lazyLoad(exports, ["ImportListLazyLibrarian"], () => require("./importListLazyLibrarian"));

export { ImportListReadarrArgs, ImportListReadarrState } from "./importListReadarr";
export type ImportListReadarr = import("./importListReadarr").ImportListReadarr;
export const ImportListReadarr: typeof import("./importListReadarr").ImportListReadarr = null as any;
utilities.lazyLoad(exports, ["ImportListReadarr"], () => require("./importListReadarr"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "readarr:ImportLists/importList:ImportList":
                return new ImportList(name, <any>undefined, { urn })
            case "readarr:ImportLists/importListExclusion:ImportListExclusion":
                return new ImportListExclusion(name, <any>undefined, { urn })
            case "readarr:ImportLists/importListGoodreadsBookshelf:ImportListGoodreadsBookshelf":
                return new ImportListGoodreadsBookshelf(name, <any>undefined, { urn })
            case "readarr:ImportLists/importListGoodreadsList:ImportListGoodreadsList":
                return new ImportListGoodreadsList(name, <any>undefined, { urn })
            case "readarr:ImportLists/importListGoodreadsOwnedBooks:ImportListGoodreadsOwnedBooks":
                return new ImportListGoodreadsOwnedBooks(name, <any>undefined, { urn })
            case "readarr:ImportLists/importListGoodreadsSeries:ImportListGoodreadsSeries":
                return new ImportListGoodreadsSeries(name, <any>undefined, { urn })
            case "readarr:ImportLists/importListLazyLibrarian:ImportListLazyLibrarian":
                return new ImportListLazyLibrarian(name, <any>undefined, { urn })
            case "readarr:ImportLists/importListReadarr:ImportListReadarr":
                return new ImportListReadarr(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("readarr", "ImportLists/importList", _module)
pulumi.runtime.registerResourceModule("readarr", "ImportLists/importListExclusion", _module)
pulumi.runtime.registerResourceModule("readarr", "ImportLists/importListGoodreadsBookshelf", _module)
pulumi.runtime.registerResourceModule("readarr", "ImportLists/importListGoodreadsList", _module)
pulumi.runtime.registerResourceModule("readarr", "ImportLists/importListGoodreadsOwnedBooks", _module)
pulumi.runtime.registerResourceModule("readarr", "ImportLists/importListGoodreadsSeries", _module)
pulumi.runtime.registerResourceModule("readarr", "ImportLists/importListLazyLibrarian", _module)
pulumi.runtime.registerResourceModule("readarr", "ImportLists/importListReadarr", _module)
