// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { GetIndexerArgs, GetIndexerResult, GetIndexerOutputArgs } from "./getIndexer";
export const getIndexer: typeof import("./getIndexer").getIndexer = null as any;
export const getIndexerOutput: typeof import("./getIndexer").getIndexerOutput = null as any;
utilities.lazyLoad(exports, ["getIndexer","getIndexerOutput"], () => require("./getIndexer"));

export { GetIndexerConfigResult } from "./getIndexerConfig";
export const getIndexerConfig: typeof import("./getIndexerConfig").getIndexerConfig = null as any;
utilities.lazyLoad(exports, ["getIndexerConfig"], () => require("./getIndexerConfig"));

export { GetIndexersResult } from "./getIndexers";
export const getIndexers: typeof import("./getIndexers").getIndexers = null as any;
utilities.lazyLoad(exports, ["getIndexers"], () => require("./getIndexers"));

export { IndexerArgs, IndexerState } from "./indexer";
export type Indexer = import("./indexer").Indexer;
export const Indexer: typeof import("./indexer").Indexer = null as any;
utilities.lazyLoad(exports, ["Indexer"], () => require("./indexer"));

export { IndexerConfigArgs, IndexerConfigState } from "./indexerConfig";
export type IndexerConfig = import("./indexerConfig").IndexerConfig;
export const IndexerConfig: typeof import("./indexerConfig").IndexerConfig = null as any;
utilities.lazyLoad(exports, ["IndexerConfig"], () => require("./indexerConfig"));

export { IndexerFilelistArgs, IndexerFilelistState } from "./indexerFilelist";
export type IndexerFilelist = import("./indexerFilelist").IndexerFilelist;
export const IndexerFilelist: typeof import("./indexerFilelist").IndexerFilelist = null as any;
utilities.lazyLoad(exports, ["IndexerFilelist"], () => require("./indexerFilelist"));

export { IndexerGazelleArgs, IndexerGazelleState } from "./indexerGazelle";
export type IndexerGazelle = import("./indexerGazelle").IndexerGazelle;
export const IndexerGazelle: typeof import("./indexerGazelle").IndexerGazelle = null as any;
utilities.lazyLoad(exports, ["IndexerGazelle"], () => require("./indexerGazelle"));

export { IndexerIptorrentsArgs, IndexerIptorrentsState } from "./indexerIptorrents";
export type IndexerIptorrents = import("./indexerIptorrents").IndexerIptorrents;
export const IndexerIptorrents: typeof import("./indexerIptorrents").IndexerIptorrents = null as any;
utilities.lazyLoad(exports, ["IndexerIptorrents"], () => require("./indexerIptorrents"));

export { IndexerNewznabArgs, IndexerNewznabState } from "./indexerNewznab";
export type IndexerNewznab = import("./indexerNewznab").IndexerNewznab;
export const IndexerNewznab: typeof import("./indexerNewznab").IndexerNewznab = null as any;
utilities.lazyLoad(exports, ["IndexerNewznab"], () => require("./indexerNewznab"));

export { IndexerNyaaArgs, IndexerNyaaState } from "./indexerNyaa";
export type IndexerNyaa = import("./indexerNyaa").IndexerNyaa;
export const IndexerNyaa: typeof import("./indexerNyaa").IndexerNyaa = null as any;
utilities.lazyLoad(exports, ["IndexerNyaa"], () => require("./indexerNyaa"));

export { IndexerTorrentRssArgs, IndexerTorrentRssState } from "./indexerTorrentRss";
export type IndexerTorrentRss = import("./indexerTorrentRss").IndexerTorrentRss;
export const IndexerTorrentRss: typeof import("./indexerTorrentRss").IndexerTorrentRss = null as any;
utilities.lazyLoad(exports, ["IndexerTorrentRss"], () => require("./indexerTorrentRss"));

export { IndexerTorrentleechArgs, IndexerTorrentleechState } from "./indexerTorrentleech";
export type IndexerTorrentleech = import("./indexerTorrentleech").IndexerTorrentleech;
export const IndexerTorrentleech: typeof import("./indexerTorrentleech").IndexerTorrentleech = null as any;
utilities.lazyLoad(exports, ["IndexerTorrentleech"], () => require("./indexerTorrentleech"));

export { IndexerTorznabArgs, IndexerTorznabState } from "./indexerTorznab";
export type IndexerTorznab = import("./indexerTorznab").IndexerTorznab;
export const IndexerTorznab: typeof import("./indexerTorznab").IndexerTorznab = null as any;
utilities.lazyLoad(exports, ["IndexerTorznab"], () => require("./indexerTorznab"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "readarr:Indexers/indexer:Indexer":
                return new Indexer(name, <any>undefined, { urn })
            case "readarr:Indexers/indexerConfig:IndexerConfig":
                return new IndexerConfig(name, <any>undefined, { urn })
            case "readarr:Indexers/indexerFilelist:IndexerFilelist":
                return new IndexerFilelist(name, <any>undefined, { urn })
            case "readarr:Indexers/indexerGazelle:IndexerGazelle":
                return new IndexerGazelle(name, <any>undefined, { urn })
            case "readarr:Indexers/indexerIptorrents:IndexerIptorrents":
                return new IndexerIptorrents(name, <any>undefined, { urn })
            case "readarr:Indexers/indexerNewznab:IndexerNewznab":
                return new IndexerNewznab(name, <any>undefined, { urn })
            case "readarr:Indexers/indexerNyaa:IndexerNyaa":
                return new IndexerNyaa(name, <any>undefined, { urn })
            case "readarr:Indexers/indexerTorrentRss:IndexerTorrentRss":
                return new IndexerTorrentRss(name, <any>undefined, { urn })
            case "readarr:Indexers/indexerTorrentleech:IndexerTorrentleech":
                return new IndexerTorrentleech(name, <any>undefined, { urn })
            case "readarr:Indexers/indexerTorznab:IndexerTorznab":
                return new IndexerTorznab(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("readarr", "Indexers/indexer", _module)
pulumi.runtime.registerResourceModule("readarr", "Indexers/indexerConfig", _module)
pulumi.runtime.registerResourceModule("readarr", "Indexers/indexerFilelist", _module)
pulumi.runtime.registerResourceModule("readarr", "Indexers/indexerGazelle", _module)
pulumi.runtime.registerResourceModule("readarr", "Indexers/indexerIptorrents", _module)
pulumi.runtime.registerResourceModule("readarr", "Indexers/indexerNewznab", _module)
pulumi.runtime.registerResourceModule("readarr", "Indexers/indexerNyaa", _module)
pulumi.runtime.registerResourceModule("readarr", "Indexers/indexerTorrentRss", _module)
pulumi.runtime.registerResourceModule("readarr", "Indexers/indexerTorrentleech", _module)
pulumi.runtime.registerResourceModule("readarr", "Indexers/indexerTorznab", _module)
